apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
      version: 3.31.0 # helm:autoupdate:datadog
  interval: 1m0s
  timeout: 10
  values:
    replicaCount: 1
